apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel1.my-apps.tap.20230727181826.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel1.my-apps.tap
  version: 20230727181826.0.0+build.ac352a6
  releaseNotes: |
    Release v20230727181826.0.0+build.ac352a6 of package tanzu-java-web-app-carvel1.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel1-my-apps-bundle@sha256:f3c0bf31b4fe6e7b2aa86bbcad9eb7d923d003df9e03d69a26e96749bd56c7d3
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

