---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: tanzu-java-web-app-carvel2
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 namespace: my-apps2
 packageRef:
   refName: tanzu-java-web-app-carvel2.my-apps2.tap # name of the Package
   versionSelection:
     constraints: 20230803063048.0.0+build.ac352a6 # version of the Package
 values:
 - secretRef:
     name: app-values # Secret created in previous step
