---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: tanzu-java-web-app-carvel
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 packageRef:
   refName: tanzu-java-web-app-carvel.my-apps.tap # name of the Package
   versionSelection:
     constraints: 20230731061039.0.0 # version of the Package
# values:
# - secretRef:
#     name: app-values # Secret created in previous step
