apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel.my-apps.tap.20230731061039.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel.my-apps.tap
  version: 20230731061039.0.0+build.ac352a6
  releaseNotes: |
    Release v20230731061039.0.0+build.ac352a6 of package tanzu-java-web-app-carvel.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel-my-apps-bundle@sha256:6f676afc2534041ebe912190574e1ec66451b2cce1c8ea27dc75f68289aed197
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

