apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel.my-apps.tap.20230731191733.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel.my-apps.tap
  version: 20230731191733.0.0+build.ac352a6
  releaseNotes: |
    Release v20230731191733.0.0+build.ac352a6 of package tanzu-java-web-app-carvel.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel-my-apps-bundle@sha256:451a201af1d161d0ae377781a5d376cf47c94f7e92ef9cdc2f096f55e2a21707
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

