apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel2.ybhagwan.tap.20230804063850.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel2.ybhagwan.tap
  version: 20230804063850.0.0+build.ac352a6
  releaseNotes: |
    Release v20230804063850.0.0+build.ac352a6 of package tanzu-java-web-app-carvel2.ybhagwan.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel2-ybhagwan-bundle@sha256:5602afa53445e1426b12356b2c9665374f87c1100db42c2ba62fb8c45ef68ba8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

