apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel22.my-apps.tap.20230921120349.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel22.my-apps.tap
  version: 20230921120349.0.0+build.ac352a6
  releaseNotes: |
    Release v20230921120349.0.0+build.ac352a6 of package tanzu-java-web-app-carvel22.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel22-my-apps-bundle@sha256:1908c07e27e650eda845cd29ff8541c9c725e17405035fa1b53c36d684277a7b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

