apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app-carvel22.my-apps.tap.20230911084847.0.0+build.ac352a6
spec:
  refName: tanzu-java-web-app-carvel22.my-apps.tap
  version: 20230911084847.0.0+build.ac352a6
  releaseNotes: |
    Release v20230911084847.0.0+build.ac352a6 of package tanzu-java-web-app-carvel22.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: tapperf.azurecr.io/performanceautomation/tanzu-java-web-app-carvel22-my-apps-bundle@sha256:7751cf00b03d92a247c97dc5d97fd95d323e1f8407c2e94b803b8c6844470d2d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

