---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: app
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 packageRef:
   refName: tanzu-java-web-app-carvel3.my-apps.tap # name of the Package
   versionSelection:
     constraints: 20230728095050.0.0 # version of the Package
